### ISSUE TITLE
Game Crashes When Trying to Play Certain Levels

### ISSUE THREAD

**Issue by MasterGamerY** [Prevter/BetterCrashlogs#3]
When trying to play certain levels, the game crashes and the crashlog says that this mod is the faulty mod. Im uncertain which specific levels the game crashes on but all my crashes occured on the first page of the awarded tab.
[2024-06-22_12-28-06.log](https://github.com/user-attachments/files/15937439/2024-06-22_12-28-06.log)

**Comment by prevter** [comment]
This is actually a chain reaction of crashes. Your game crashed due to some other reason (you might be able to find a crashlog with the same date/time in your crashlogs folder).
That crash somehow broke OpenGL and crashed BetterCrashlogs window leading to a second crashlog.
